FROM jboss/wildfly

RUN  /opt/jboss/wildfly/bin/add-user.sh admin password --silent
ADD  DC/ /opt/jboss/wildfly/standalone/configuration/DC/
ADD  device-controllers-ear.ear /opt/jboss/wildfly/standalone/deployments/

CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]
